name: publish
on: [push]
jobs:
publish-jbcaip:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GH_TOKEN }}
- name: Build and publish the jbcaip Docker image
run: |
       docker build . --tag ghcr.io/JacksonBarker/jbcaip:latest
       docker run ghcr.io/JacksonBarker/jbcaip:latest
       docker push ghcr.io/JacksonBarker/jbcaip:latest